version: '3.4'

services:
  api:
    build: api
    command: sh /app/api.sh
    ports:
      - 8000:80
    depends_on:
      - rabbitmq
    volumes:
      - ./api:/app

  listener:
    build: listener
    command: sh /usr/src/app/script.sh
    depends_on:
      - rabbitmq
    volumes:
      - ./listener:/usr/src/app

  rabbitmq:
    image: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: "user"
      RABBITMQ_DEFAULT_PASS: "pass"
      RABBITMQ_DEFAULT_VHOST: "/"
    expose:
      - 5672

  db:
    image: postgres
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: devops
      POSTGRES_USER: devops
      POSTGRES_PASSWORD: devops
    expose:
      - 5432 
